jaco_hand_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 125

jaco_hand_joint_traj_controller:
  type: effort_controllers/JointTrajectoryController
  joints: &hand_joints
    - hand_finger_joint_0
    - hand_finger_joint_2
    - hand_finger_joint_4
  gains: # Required because we're controlling an effort interface
    hand_finger_joint_0: {p: 10, i: 0.0001, d: 0.005}
    hand_finger_joint_2: {p: 10, i: 0.0001, d: 0.005}
    hand_finger_joint_4: {p: 10, i: 0.0001, d: 0.005}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    hand_finger_joint_0: {trajectory: 0.1, goal: 0.1}
    hand_finger_joint_2: {trajectory: 0.1, goal: 0.1}
    hand_finger_joint_4: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 10

jaco_hand_joint_group_eff_controller:
  type: effort_controllers/JointGroupEffortController
  joints: *hand_joints