robotiq_hand_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 100

robotiq_hand_joint_traj_controller:
  type: effort_controllers/JointTrajectoryController
  joints: &hand_joints
    - hand1_finger_middle_joint_1
    - hand1_finger_middle_joint_2
    - hand1_finger_middle_joint_3
    - hand2_1_palm_finger_1_joint
    - hand2_finger_1_joint_1
    - hand2_finger_1_joint_2
    - hand2_finger_1_joint_3
    - hand3_1_palm_finger_2_joint
    - hand3_finger_2_joint_1
    - hand3_finger_2_joint_2
    - hand3_finger_2_joint_3

  gains: # Required because we're controlling an effort interface
    hand2_1_palm_finger_1_joint: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand2_finger_1_joint_1: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand2_finger_1_joint_2: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand2_finger_1_joint_3: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand3_finger_2_joint_1: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand3_finger_2_joint_2: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand3_finger_2_joint_3: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand1_finger_middle_joint_1: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand1_finger_middle_joint_2: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand1_finger_middle_joint_3: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand3_1_palm_finger_2_joint: {p: 100, i: 1, d: 1, i_clamp: 1}

  constraints:
    goal_time: 0.8
    stopped_velocity_tolerance: 0.05
    hand2_1_palm_finger_1_joint: {trajectory: 0.1, goal: 0.15}
    hand2finger_1_joint_1: {trajectory: 0.1, goal: 0.15}
    hand2finger_1_joint_2: {trajectory: 0.1, goal: 0.15}
    hand2finger_1_joint_3: {trajectory: 0.1, goal: 0.15}
    hand3finger_2_joint_1: {trajectory: 0.1, goal: 0.15}
    hand3finger_2_joint_2: {trajectory: 0.1, goal: 0.15}
    hand3finger_2_joint_3: {trajectory: 0.1, goal: 0.15}
    hand1finger_middle_joint_1: {trajectory: 0.1, goal: 0.15}
    hand1finger_middle_joint_2: {trajectory: 0.1, goal: 0.15}
    hand1finger_middle_joint_3: {trajectory: 0.1, goal: 0.15}
    hand3_1_palm_finger_2_joint: {trajectory: 0.1, goal: 0.15}

  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 10

robotiq_hand_joint_group_eff_controller:
  type: effort_controllers/JointGroupEffortController
  joints: *hand_joints