joint_names:
  - hand1_finger_middle_joint_1
  - hand1_finger_middle_joint_2
  - hand1_finger_middle_joint_3
  - hand2_1_palm_finger_1_joint
  - hand2_finger_1_joint_1
  - hand2_finger_1_joint_2
  - hand2_finger_1_joint_3
  - hand3_1_palm_finger_2_joint
  - hand3_finger_2_joint_1
  - hand3_finger_2_joint_2
  - hand3_finger_2_joint_3
joint_positions_open:
  hand1_finger_middle_joint_1: 0.0
  hand1_finger_middle_joint_2: 0.0
  hand1_finger_middle_joint_3: 0.0
  hand2_1_palm_finger_1_joint: 0.0
  hand2_finger_1_joint_1: 0.0
  hand2_finger_1_joint_2: 0.0
  hand2_finger_1_joint_3: 0.0
  hand3_1_palm_finger_2_joint: 0.0
  hand3_finger_2_joint_1: 0.0
  hand3_finger_2_joint_2: 0.0
  hand3_finger_2_joint_3: 0.0
topic_pub: '/robotiq_hand_joint_traj_controller/command'