schunk_hand_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 125

schunk_hand_joint_traj_controller:
  type: effort_controllers/JointTrajectoryController
  joints: &hand_joints
    - hand_11_knuckle_joint
    - hand_12_finger_joint
    - hand_13_finger_joint
    - hand_22_finger_joint
    - hand_23_finger_joint
    - hand_32_thumb_joint
    - hand_33_thumb_joint
  gains: # Required because we're controlling an effort interface
    hand_11_knuckle_joint: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand_12_finger_joint: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand_13_finger_joint: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand_22_finger_joint: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand_23_finger_joint: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand_32_thumb_joint: {p: 100, i: 1, d: 1, i_clamp: 1}
    hand_33_thumb_joint: {p: 100, i: 1, d: 1, i_clamp: 1}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    hand_11_knuckle_joint: {trajectory: 0.1, goal: 0.1}
    hand_12_finger_joint: {trajectory: 0.1, goal: 0.1}
    hand_13_finger_joint: {trajectory: 0.1, goal: 0.1}
    hand_22_finger_joint: {trajectory: 0.1, goal: 0.1}
    hand_23_finger_joint: {trajectory: 0.1, goal: 0.1}
    hand_32_thumb_joint: {trajectory: 0.1, goal: 0.1}
    hand_33_thumb_joint: {trajectory: 0.1, goal: 0.1}

  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 10

schunk_hand_joint_group_eff_controller:
  type: effort_controllers/JointGroupEffortController
  joints: *hand_joints