joint_names:
  - hand_11_knuckle_joint
  - hand_12_finger_joint
  - hand_13_finger_joint
  - hand_22_finger_joint
  - hand_23_finger_joint
  - hand_32_thumb_joint
  - hand_33_thumb_joint
joint_positions_open:
  hand_11_knuckle_joint: 0.0
  hand_12_finger_joint: -0.5
  hand_13_finger_joint: -0.5
  hand_22_finger_joint: -0.5
  hand_23_finger_joint: -0.5
  hand_32_thumb_joint: -0.5
  hand_33_thumb_joint: -0.5
topic_pub: '/schunk_hand_joint_traj_controller/command'